version: "3.7"

services:
  nginx:
    build: ./nginx
    container_name: ${NAMESPACE}_nginx
    image: ${NAMESPACE}/nginx
    depends_on:
      - php
    working_dir: ${WORKDIR_SERVER}
    ports:
      - 80:80
      - 443:443
    volumes:
      - app_data:${WORKDIR_SERVER}:delegated

  php:
    build:
      context: ./php
      args:
        PHP_VERSION_SET: ${PHP_VERSION_SET}
        PHP_VERSION_SET_IMAGE: php:${PHP_VERSION_SET}-fpm-alpine3.8
        PHP_BUILD_DIR: ${PHP_BUILD_DIR}
    container_name: ${NAMESPACE}_php_${PHP_VERSION_SET}
    image: ${NAMESPACE}/php_${PHP_VERSION_SET}
    working_dir: ${WORKDIR_SERVER}
    depends_on:
      - mysql
      - redis
      - mailhog
    volumes:
      - app_data:${WORKDIR_SERVER}:delegated

  mysql:
    build: ./mysql
    container_name: ${NAMESPACE}_mysql
    image: ${NAMESPACE}/mysql
    ports:
      - ${DATABASE_PORT_EXTERNAL}:3306
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}

  redis:
    build: ./redis
    image: ${NAMESPACE}/redis
    container_name: ${NAMESPACE}_redis
    ports:
      - 6379:6379
    sysctls:
      net.core.somaxconn: '1024'

  mailhog:
    image: mailhog/mailhog:latest
    container_name: ${NAMESPACE}_mailhog
    expose:
      - 1025
    ports:
      - 8025:8025

volumes:
  app_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${WORKDIR}"